### ISSUE TITLE
Storage in mimo-example

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/urbs#119]
According to the mimo-example input data for "Storage", the charging and discharging efficiencies are both 0.40, which means that the full cycle efficiency is 0.16. Is this correct? I expected the full cycle efficiency to be between 0.30 and 0.40, as mentioned in this website for example [1].

[1] http://energystorage.org/energy-storage/technologies/hydrogen-energy-storage

**Comment by KSchoenleber** [comment]
Your interpretation is correct. The circle efficiency would be 0.16 in the given case. I guess this is just wrongly set-up. If you want it fixed, please make it an issue. At some point I will close those.
