### ISSUE TITLE
speedup potential: def def_costs_rule

### ISSUE THREAD

**Issue by tzipperle** [tum-ens/urbs#141]
I think there is further speedup potential at `def def_costs_rule(m, cost_type):` for the same reason as in PR #140. As you can see in the cProfile graph for [mimo-example base 8760](https://github.com/tum-ens/urbs/files/1197659/urbs_base.pdf) this method needs a lot of time.

Maybe is there also useful to change the data structure from pandas DataFrame to a dict?

**Comment by KSchoenleber** [comment]
This issue is closed by pull request 168
