### ISSUE TITLE
Problems with pandas release 0.21

### ISSUE THREAD

**Issue by KSchoenleber** [tum-ens/urbs#164]
Apparently the newest pandas release causes problems with the buy-sell feature in current form.

**Comment by maledo** [comment]
Which problems exactely? Or are you referring to the warnings regarding sort_level?

**Comment by lnksz** [comment]
FYI:
https://github.com/tum-ens/rivus/issues/25

**Comment by KSchoenleber** [comment]
Thanks Kristof perhaps that helps

**Comment by maledo** [comment]
Closed via #175
