### ISSUE TITLE
Double saving of model as .h5--> emtpy result

### ISSUE THREAD

**Issue by Leonhard-B** [tum-ens/urbs#172]
Using the save command in front and after calling the solver (gurobi) leads to empty results; the files unsolved.h5 and solved.h5 have exactly the same size and content. The program (runme.py) still compiles and executes properly, but the result diagrams contain no data except for the demand for power:

![scenario_base-elec-north-mid-south-all](https://user-images.githubusercontent.com/35296369/35100139-ee4c9f58-fc5a-11e7-96a7-aa9a24cf0740.png)

I executed the runme.py of the current master branch and added the second save command in line 118, after creating the model called prob.

   urbs.save(prob, os.path.join(result_dir, '{}.h5'.format('unsolved')))
   result = optim.solve(prob, tee=True)
   urbs.save(prob, os.path.join(result_dir, '{}.h5'.format('solved')))

@maledo: Removing all options to sell or buy power (this includes to modify the mimo-example.xlsx and comment lines 46, 55,67, 98 and 107 in input.py) does not change the behavior of this error.

**Comment by maledo** [comment]
As the result cache is only created if there is no _result element (c.f. [saveload.py](https://github.com/tum-ens/urbs/blob/90651b637ab83db4b4317695586e9ef450c009a3/urbs/saveload.py#L34)), the cache is not updated anmyore, hence the result is still empty. If the lines are commented out, it will load the cache again.
