### ISSUE TITLE
usage of dual variables -> get_entity in pyomoio.py causes script failure

### ISSUE THREAD

**Issue by Leonhard-B** [tum-ens/urbs#173]
When setting dual=True in the urbs.create_model function it is not possible to save the model as an .h5 file. Backtracking showed that the issues takes place in pyomoio.py in line 55 inside the function 'get_entity'. The path is as follows: 
urbs.save(prob) [in runme.py] ->save [saveload.py] -> create_result_cache [saveload.py] -> get entity [pyomoio.py]

The error message is as follows: 
KeyError: 'Component with name: res_buy_step[3501,North,Elec buy,Buy] (id=2952272094312)'
There are only few entities causing the crash:
res_buy_step
res_buy_total
res_sell_step
res_sell_total
res_env_step
res_env_total
res_stock_step
res_stock_total

I excluded these by is inserting
if entity == 'res_buy_step': continue    (etc.)
in the create_result_cache command before calling get_entity (prob, entity). Like this the script worked fine. I saved the data of the resulting model, which contains the dual variables, to an excel sheet (see attachment).

When modifying the mimo-example.xlsx data sheet (all entrances of buy-sell set to zero and transmission capacity set to zero, see attachment) number one to four of the above mentioned entities do not cause script failure any more.

Pinpointing the error showed that 
instance.dual[v[1]]
Causes the following error message:
*** KeyError: 'Component with name: res_buy_step[3501,South,Elec buy,Buy] (id=1974341189544)'
Other entities like 'def_dsm_variables' worked fine with this exact command and showed the corresponding dual variable.

[dual.xlsx](https://github.com/tum-ens/urbs/files/1652827/dual.xlsx)
[mimo-example.xlsx](https://github.com/tum-ens/urbs/files/1652831/mimo-example.xlsx)

**Comment by Leonhard-B** [comment]
All constrains get the parameter com_tuples when being initialized in model.py in the function create_model. 
The only other constrain which gets com_tuples and works properly is res_vertex.
com_tuples include the different tuples (site, commodity, type) of 'commodity' in mimo-example.xlsx, like 'Mid, Lignite, Stock'.
Maybe this causes the issue; at least it makes the above mentioned entities quite unique.

**Comment by Leonhard-B** [comment]
Setting all the entries in 'mimo-example' in commodities that have 'Inf' to 1000000000 seems to solve athe trouble with the dual variables. The resulting model contains all the above mentioned entities with their dual variables.

**Comment by maledo** [comment]
With the current version, the problem lies within the set differences which are used for the definition of the constraints, e.g. https://github.com/tum-ens/urbs/blob/d2a86f73ce34ce553598fec145b6b39ee22a88e1/urbs/model.py#L432-L436

They cause a problem in pyomoio
https://github.com/tum-ens/urbs/blob/d2a86f73ce34ce553598fec145b6b39ee22a88e1/urbs/pyomoio.py#L218-L222
as they don't have a specific domain name.

I'm not yet sure, whether they are needed. I will investigate further.

**Comment by maledo** [comment]
So, I found the commit, on which we started introducing set differences for constraint definitions instead on working on already existing sets: https://github.com/tum-ens/urbs/commit/e90fd387b713bd151a391b9082972d7cc584079e

Working with this stage, the upper description of @Leonhard-B holds.
