### ISSUE TITLE
Problem, when sites in site sheet does not match with the sites in transmission, process, etc... sheets.

### ISSUE THREAD

**Issue by oakca** [tum-ens/urbs#182]
[Validation.py ](https://github.com/tum-ens/urbs/blob/master/urbs/validation.py) should also check if the sites in site sheet are equal to sites in transmission or process sheets. Type-Errors inside input file raise errors when model is run. A simple string check would be great, and better than checking manually, if there is a wrong-typed site in any input sheets.

**Comment by maledo** [comment]
Closed by #197
