### ISSUE TITLE
urbs.save of h5-file not possible for 1-node models

### ISSUE THREAD

**Issue by KSchoenleber** [tum-ens/urbs#196]
Currently in 1-node models the urbs.save line has to be commented out.

**Comment by kbareiss** [comment]
Would like to reopen that issue.
h5 file still not possible to be written in a 1-node problem (latest version).
    to comment out "  save(prob, os.path.join(result_dir, '{}.h5'.format(sce))) "
solves the problem (as stated in previous comment)

**Comment by lodersky** [comment]
Release 1.0 fixes this issue.
