### ISSUE TITLE
Refactor `urbs.plot` into several smaller functions

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#2]
The plotting function is too big and does too many things. There should be individual functions for
- creating the figure/subplots
- calling the `get_*` functions and prepare data for plotting
- decoration
- layout

When looking towards the use in `runme.py` 1-2 more involved helper functions could even take care for creating multiple plots for a single `prob` instance when handed a list of lists or an options dict with a suitable input format.

**Comment by smuellr** [comment]
Additional to the plotting of energy and storage a plot of the costs (variable and/or fix) of the appearing processes might be interesting. The user could determine the size of the figure, number and arrangement of subplots and their content as input arguments for urbs in the run script.

**Comment by ojdo** [comment]
First step would probably to factor out the two subplots into separate functions. The plot function itself should become more like the pandas plot functions as a hub for many, many optional ``**kwds`` arguments that are then brokered to the respective drawing, decoration and layout functions.

**Comment by ojdo** [comment]
Long-term idea: this modularisation should/could lead to finally split urbs into several files, each with a short, descriptive name and clear responsibility like `plot`, `model` and `io`.
