### ISSUE TITLE
Style: pyomo_model_prep is missing the doc string

### ISSUE THREAD

**Issue by maledo** [tum-ens/urbs#201]
The relatively new function `pyomo_model_prep` in input.py (cf [input, line 94](https://github.com/tum-ens/urbs/blob/34c916e9fe2b5692bd19782c4e3637ff7e3fa12d/urbs/input.py#L94)) is missing the doc string which shows the information about the function with its input and output arguments. E.g. """ Prepare pyomo model data""" and so on.

**Comment by lodersky** [comment]
Documentation was added.
