### ISSUE TITLE
penalise excess production

### ISSUE THREAD

**Issue by brsk2k** [tum-ens/urbs#203]
Hello,

is it possible to penalise excess production - as to avoid meaningless exchange of energy between sides and "wrong" sizing of, for instance, renewable capacities. Any suggestions / functions I could use?

Many thanks!

**Comment by sonercandas** [comment]
First of all, you can define a new dummy process in each site namely "Curtailment" whose capacity is allowed to expand free of charge. This process would take "Elec" as an input and in turn generate no output. 
You can then attach variable costs to this process to introduce a penalty for each kWh excess production curtailed as you mentioned.
