### ISSUE TITLE
LP HAS NO PRIMAL FEASIBLE SOLUTION for scenario_co2_tax_mid

### ISSUE THREAD

**Issue by Leonhard-B** [tum-ens/urbs#209]
It seems like the programm is unable to solve the model of the scenario_co2_tax_mid. Depending of the version of matlotlib this is either handled by plotting empty graphs or by throwing an exception. In the first case the programm finishes normally, except for telling LP HAS NO PRIMAL FEASIBLE SOLUTION if tee is set True. The graphs are empty except for the demand curve.
The funny thing is, that the newer version of matplotlib is throwing the exception and the older one is capable of handling the results (by not doing the plotting).
[output scenario_co2_tax_mid.txt](https://github.com/tum-ens/urbs/files/2589416/output.scenario_co2_tax_mid.txt)

**Comment by Leonhard-B** [comment]
The exception above only happens if 'objective' is set to 'CO2' (a new feature introduced by merge at 07.11.2018).
Maybe this is related to the fact that making CO2 expensive has no effect on the optimzation task to minimize CO2. Fixing the value for South|Mid|North-CO2-Env in 'commodity to zero could be a workaraound. In this concrete case the scenario_co2_tax_mid could also check for the objective and become a scenario_base in case it is 'CO2. Last but not least one might simply omit the scenario since it makes no sense in combination with minimizing CO2.

**Comment by maledo** [comment]
Thank you for that comment, I actually wanted to start an issue about that just now.
