### ISSUE TITLE
Error in validation.py

### ISSUE THREAD

**Issue by KSchoenleber** [tum-ens/urbs#219]
Right now for each site specified there has to be a corresponding process, storage and transmission set. Otherwise a validation error will occur. This is not the desired behavior, since, e.g., a site without storage should be possible.

**Comment by kbareiss** [comment]
I strongly reccomend not to publish bugs which are known. I suggest either to remove the entry or change it. Not familiar to python language but it should look like following...

if not data['storage'].empty:
        for site in data['storage'].index.tolist():
            if site not in data['site'].index.levels[0].tolist():
                raise KeyError("All names in the column 'Site' in input "
                               "worksheet 'Storage' must be from the list of "
                               "site names specified in the worksheet 'Site'.")

**Comment by lodersky** [comment]
With this version I get an error in plot.py line 240, if a site is defined without storage. The axis of the plot can not be generated, as 'stored' is empty for this site:
'ValueError: operands could not be broadcast together with shapes (169,) (0,)'

**Comment by lodersky** [comment]
Fixed with commit f92f290d4dd63a7cf.

Closing this issue.
