### ISSUE TITLE
Clarify meaning of input/output ratios in entity process-commodity

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#22]
When switiching from single-input-single-output to multiple-input-multiple-output processes, the concept of "process efficiencies" was generalised to "process input/output ratios". The documentation is not yet clearly pointing out how to convert from efficiencies (output energy per input energy) to a set of input/output ratios. The connection to the process investment costs and the capcity variable `cap-pro` should be mentioned, too.
#### Writer's note

> Input/output ratios add one degree of freedom when choosing their values. The scaling used in the example file `mimo-example.xlsx` shows one possible choice: in the example, input ratios are set to 1, while the output ratios are equal to the _electric efficiency_ `eff` (e.g. `0.4`) of conversion processes. This means: for one unit of process through-put (variable `tau-pro`) a yield of `1 * eff` electricity is generated. As the through-put is responsible for the capacity requirement (variable `cap-pro`), the input ratio of 1 means that the capacity investment costs (process attribute `inv-cost`) is therefore to be entered in terms of **input capacity** (i.e. "thermal power plant capacity" or `EUR/MW_thermal`). This can be confusing.
> 
> If one wants to enter investment costs in terms of electrical **output capacity** (i.e. "electrical power plant capacity" or `EUR/MW_electric`), the output-ratio for the electric output must be set to one, and the corresponding input ratio must be set to the inverse value `1 / eff` (e.g. `1 / 0.4 = 2.5`). This is to be read as: "for one unit of electrical output, 1/eff units of the input commodity are needed." That way, the through-put variable changes in meaning from "thermal fuel conversion rate" to "electrical power ouptut rate" and thus the installed capacity variable value is lower for a given physical power plant size.

**Comment by LogiMad** [comment]
Considering the aforementioned note, if the capacity of a power plant is not fixed as electricity but flexible to be set based on different types of power (e.g.: electrical, thermal, hydraulic), then the commodity might need to be added in process capacity tuple set. This also helps to include process like CHP plants to have independent capacity for different commodities.
As normally the capacity of a power plant is defined based on output capacity (MW_electrical), one should proceed with setting the input ratio to 1/eff, while the eff is related to output commodity like electricity. Although this can be used as a work around in case of single output process, for multiple output processes (e.g.: Electricity+CO2, Electricity+Heat), this definition may not work as the multiple output efficiencies could not possibly be combined and inversed to set as input ratio. Then what is the solution?

**Comment by lodersky** [comment]
It is clarified in the [documentation](https://urbs.readthedocs.io/en/latest/implementdoc/param-tech.html#process-technical-parameters): 
>Since all costs and capacity constraints take the process throughput τyvpt as the reference, it is reasonable to assign an in- or output ratio of “1” to at least one commodity. The flow of this commodity then tracks the throughput and can be used as a reference. All other values of in- and output ratios can then be adjusted by scaling them by an appropriate factor to the reference commodity flow.
