### ISSUE TITLE
problem with mult-regional model but not all connected through transmission lines

### ISSUE THREAD

**Issue by kbareiss** [tum-ens/urbs#225]
It seems like having a multi-regional model where not all regions are connected at least to one region via transmission 'lines' causes following key error "none of [index(['site'],dtype='object'. name='sit_')] are in the [colums]. The error occurs at the function: imported = imported.unstack(level='sit_')[sites].fillna(0).sum(axis=1). 
Just from reading the comment in the code it seems like a list of "transmittable" commodities are defined when one region is using this, which than has to be valid for all sites. The workaround of defining transmission lines for those regions which have not (with an capacity of 0) solves the problem.

**Comment by lodersky** [comment]
The problem should be solved with the new version of urbs (v1.0).
