### ISSUE TITLE
urbs runduals - different results depending on selected solver

### ISSUE THREAD

**Issue by IngaMueller** [tum-ens/urbs#229]
The glpk solver and the gurobi solver do not give the same results for dual variables. 

The glpk solver provides the following results:
![grafik](https://user-images.githubusercontent.com/31440909/54001458-2057c180-4197-11e9-8d6b-ce105fc351f8.png)

whereas gurobi gives other results which seems to be more plausible, as only PV in site onenode is installable:
![grafik](https://user-images.githubusercontent.com/31440909/54001487-36fe1880-4197-11e9-9c6d-49f6a9003a18.png)

This could be a solver issue rather than an urbs issue?

**Comment by maledo** [comment]
I think, this is indeed more of a solver issue. And an interpretation question.
