### ISSUE TITLE
Storage Charge and Discharge simultaneously 

### ISSUE THREAD

**Issue by brsk2k** [tum-ens/urbs#241]
Hello
I have a site that runs a CHP, producing heat and electricity. Only heat storage is allowed at that site.
Since electricity has a high value (can be sold at high prices), the CHP utilization is maximised (cost optimization). 
Because of that, it seems like the heat storage is charging and discharging simultaneously in order to “waste” heat during the process, so that more electricity can be produced. In reality this is not possible. 
My questions:
Charging and discharging simultaneously should not be possible? – Is it possible I am mistaken in some of my inputs?
Are there any ideas / constraints to implement to avoid this issue? 

![Knipsel](https://user-images.githubusercontent.com/43682698/56296357-a0762d00-612e-11e9-8fba-5223ecbbe40f.JPG)

**Comment by brsk2k** [comment]
The only interim way I found to solve the above was to increase the variable costs in/out (€/MWh) for input or output of energy per MWh_out stored or retrieved. Although my cost assumption is small (0.5 €/MWh) I believe it is a bit of a drawback and influences results in a negative way. In reality this cost is lower - almost zero - but then I get the behaviour as shown above.

**Comment by lodersky** [comment]
It is true that charging/discharging in the same time step is not realistic. But it is not easy to define a constraint for it.

After looking into your problem, I think it's not as unrealistic as it might seem. The profit from selling electricity is higher than the cost of gas. So the model wants to increase its profit and wastes heat. The waste of heat by simultaneous charing and discharging is like a curtailment of heat (heat release to the air in reality). 

A solution to this problem would be to add a new process with the input commodity "heat" and without output. The cost of this process should be zero. In the file "mimo-example.xlsx" you will find the shortening process for electricity. Thus the waste of heat is explicitly represented in the model results.
