### ISSUE TITLE
Installation error: running runme.py  AttributeError: module 'pandas.core' has no attribute 'index'

### ISSUE THREAD

**Issue by Jinyoung6177** [tum-ens/urbs#284]
Hi, I am quite new to programming and installing the urbs on my Mac OS. I somehow succeeded to create environment via anaconda. 
I can activate urbs via anaconda but cannot run the runme.py with python. I get errors. 
And also upgrading pyutilib to version 5.8.0 doesn't help me solve the problem and it says this version won't be compitable with the latest pyomo. 
Below is my code in Terminal. 

`(myenv) yunjin-yeong-ui-MacBook-Air:pythonProject1 YUNJINYOUNG$ conda activate urbs`
`(urbs) yunjin-yeong-ui-MacBook-Air:pythonProject1 YUNJINYOUNG$ cd ~/urbs-master`
`(urbs) yunjin-yeong-ui-MacBook-Air:urbs-master YUNJINYOUNG$ python3 runme.py`
`Traceback (most recent call last):`
`File "/Users/YUNJINYOUNG/urbs-master/runme.py", line 60, in <module>`
`   prob = urbs.run_scenario(input_path, solver, timesteps, scenario,`
`File "/Users/YUNJINYOUNG/urbs-master/urbs/runfunctions.py", line 89, in run_scenario`
`   data = read_input(input_files, year)`
`File "/Users/YUNJINYOUNG/urbs-master/urbs/input.py", line 177, in read_input`
`if isinstance(data[key].index, pd.core.index.MultiIndex):`
`AttributeError: module 'pandas.core' has no attribute 'index'`

Could you help me solve this problem? Thanks a lot!

**Comment by Dthushara246** [comment]
urbs work with certain versions of the packages. It seems like you are running pandas and pyomo with latest versions.
Check the versions of the following packages in the environment urbs:
pandas = 0.24.2
pyomo = 5.6.7
pyutilib = 5.8.0
You can check them after activating the urbs by typing: conda list
You can install the correct versions of the packages using the following commands:
conda install pandas=0.24.2
conda install -c conda-forge pyomo=5.6.7
conda install pyutilib=5.8.0

**Comment by Jinyoung6177** [comment]
oh thanks a lot! It worked!




> urbs work with certain versions of the packages. It seems like you are running pandas and pyomo with latest versions.
> Check the versions of the following packages in the environment urbs:
> pandas = 0.24.2
> pyomo = 5.6.7
> pyutilib = 5.8.0
> You can check them after activating the urbs by typing: conda list
> You can install the correct versions of the packages using the following commands:
> conda install pandas=0.24.2
> conda install -c conda-forge pyomo=5.6.7
> conda install pyutilib=5.8.0

oh thanks a lot! It works well now 👍 
Apparently the version of pyutilib was at 6.0.0. 
I thought I downgraded it a few times already, but maybe not in the right env..? 

Anyway, thank you for your help!
