### ISSUE TITLE
DC power flow equation unit

### ISSUE THREAD

**Issue by JuliusSan** [tum-ens/urbs#288]
Hello,
I am currently writing my "Semesterarbeit" at the "Lehrstuhl für elektrische Energiesysteme" at the TUM and i saw your urbs document, which helps me with my DC-power-flow model, but I have a question about the DC-power flow equation:
https://urbs.readthedocs.io/en/latest/theorydoc/multinode_prob.html#dc-power-flow-equation

The input parameter to the equation are reactance in [p.u.] and voltage angle difference [°]. The documentation says, that there will be another input parameter, the basevoltage in [kV] in order to convert the power flow from [p.u.] in [MW].

Since the voltage angle difference gets converted to radiant, and the reactance is given in [p.u.], I don't understand, why the factor of the squared basevoltage would be necessary. Wouldn't it make sense to convert the power flow by multiplying the power flow with the basepower instead of the squared basevoltage?

Or is it possible, that the reactance is actually not given in [p.u], but much rather in [Ω], so that the units [kV^2/Ω = kW] ?

I am really looking forward to your help.

Kind Regards,
Julius S.

**Comment by sonercandas** [comment]
Dear Julian, you are right, the reactance should be input in Ohms, instead of per unit (on the Excel file, you can see this when you click on the column label "reactance"). We will fix the documentation accordingly.  Thanks for the warning!
