### ISSUE TITLE
runme.py no execute properly

### ISSUE THREAD

**Issue by beego98** [tum-ens/urbs#291]
Hello

When I try to execute runme.py I obtain the follow error:
ValueError: The following indices are duplicated MultiIndex([(2021, nan, nan, nan)],
           names=['support_timeframe', 'Site', 'Storage', 'Commodity'])

I tried with python3

Could you help me? Thanks

**Comment by kais-siala** [comment]
Hi beego98,

I had encountered that error before. Are you sure you are using the correct environment? I think your pandas version is newer than the one required by urbs (0.24.x).

**Comment by beego98** [comment]
Hi kais-siala,
Could you send me a requierement.txt with the packages necessary and then I'll try to install and execute de file.

**Comment by beego98** [comment]
> Hi beego98,
> 
> I had encountered that error before. Are you sure you are using the correct environment? I think your pandas version is newer than the one required by urbs (0.24.x).



> Hola beego98,
> 
> Había encontrado ese error antes. ¿Está seguro de que está utilizando el entorno correcto? Creo que su versión de pandas es más nueva que la requerida por urbs (0.24.x).

**Comment by kais-siala** [comment]
it is already in the master branch, called urbs-env.yml
try to follow the installation instructions!

**Comment by beego98** [comment]
Hi,
I install the packages necessary and I obtain run the file runme.py but when I run the file comp.py I obtain the follow error:
ValueError: No objects to concatenate

Furthermore, when I try to run the file run_intertemporal.py I obtain the following:
Added a global Cost limit for 2019.0 with the value: inf.
Added a global Cost limit for 2024.0 with the value: inf.
Added a global Cost limit for 2029.0 with the value: inf.
Added a global Cost limit for 2034.0 with the value: inf.
Killed

Could you help me?

**Comment by lodersky** [comment]
Hi,
you're probably running out of memory on your computer while creating the pyomo model. Maybe reduce the problem size (by reducing the time steps) or run the problem on a computer with more memory.

**Comment by sonercandas** [comment]
For reducing your timesteps without losing the "big picture" in your model, you might want to have a look at the typeday feature that @DZinsmeister had implemented: https://github.com/DZinsmeister/urbs/tree/Typeday
