### ISSUE TITLE
String indices error with pandas 0.17.0

### ISSUE THREAD

**Issue by maledo** [tum-ens/urbs#31]
An update to pandas 0.17.0 leads to an error in the read_excel function. The line <code>index_col=['Site', 'Commodity', 'Type']</code> raises an error as pandas expects integers instead of strings.

**Comment by ojdo** [comment]
Argh, now my using undocumented features of the `pd.ExcelFile.parse` function bites me. The `index_col` function argument always just was supposed to support integers (or lists of integers) for determining which column(s) to use for the index.
