### ISSUE TITLE
Change conversion parameters in scenarios.py

### ISSUE THREAD

**Issue by philippklughardt** [tum-ens/urbs#313]
Dear urbs community,

I would like to change some input/output ratios in the Process-Commodity tab within a scenario.
Unfortunately, after defining `pro_co = data['process-commodity']` in scenarios.py, I get the following error message when running the model: `KeyError: 'process-commodity'`

Has someone encountered this problem and could help me out? Thanks a lot in advance!

**Comment by ojdo** [comment]
The key is called `process_commodity`: https://github.com/tum-ens/urbs/blob/6368500ca32461dfe135c9427f240f2ca7b7f475/urbs/input.py#L160-L173
