### ISSUE TITLE
General problems with installation following the instructions

### ISSUE THREAD

**Issue by lu-boe** [tum-ens/urbs#314]
Hey there! 
First I would like to ask which Python version is suitable for urbs? Because on the website https://github.com/tum-ens/urbs/blob/master/README.md#installation Version 3.6 or 2.7 is stated. In the   ##README.md File in the zip-Folder it says Version 3.5 or 2.7.
Thanks in advanve for any help. Highly appreciated! 
I tried several times to install. When following the procedure (executing runme.py and comp.py) this happens: 

(base) C:\Users\lukas>conda activate urbs

(urbs) C:\Users\lukas>py --version
Python 3.6.13 :: Anaconda, Inc.

(urbs) C:\Users\lukas>cd C:\Users\lukas\OneDrive\Desktop\Programme_Installation\urbs\urbs-1.0.1\urbs-1.0.1

(urbs) C:\Users\lukas\OneDrive\Desktop\Programme_Installation\urbs\urbs-1.0.1\urbs-1.0.1>python runme.py
GLPSOL--GLPK LP/MIP Solver 5.0
Parameter(s) specified in the command line:
 --log result\Mimo-ex-20220217T1424\scenario_base.log --write C:\Users\lukas\AppData\Local\Temp\tmpwgdr34og.glpk.raw
 --wglp C:\Users\lukas\AppData\Local\Temp\tmpixcq5bka.glpk.glp --cpxlp C:\Users\lukas\AppData\Local\Temp\tmpunszp_om.pyomo.lp
Reading problem data from 'C:\Users\lukas\AppData\Local\Temp\tmpunszp_om.pyomo.lp'...
123371 rows, 129172 columns, 520448 non-zeros
1019811 lines were read
Writing problem data to 'C:\Users\lukas\AppData\Local\Temp\tmpixcq5bka.glpk.glp'...
824412 lines were written
GLPK Simplex Optimizer 5.0
123371 rows, 129172 columns, 520448 non-zeros
Preprocessing...
73820 rows, 83528 columns, 380839 non-zeros
Scaling...
 A: min|aij| =  2.463e-04  max|aij| =  1.400e+04  ratio =  5.684e+07
GM: min|aij| =  2.477e-01  max|aij| =  4.038e+00  ratio =  1.630e+01
EQ: min|aij| =  6.134e-02  max|aij| =  1.000e+00  ratio =  1.630e+01
Constructing initial basis...
Size of triangular part is 73808
      0: obj =   2.622769069e+11 inf =   7.911e+07 (2883)
   1126: obj =   3.578967540e+11 inf =   6.827e+07 (1969) 6
   2168: obj =   4.087411140e+11 inf =   6.542e+07 (1781) 5
   3086: obj =   4.541193916e+11 inf =   6.289e+07 (1544) 6
   3936: obj =   5.028769597e+11 inf =   6.084e+07 (1229) 5
   4820: obj =   6.178339312e+11 inf =   5.879e+07 (996) 6
   5639: obj =   9.652215159e+11 inf =   5.708e+07 (919) 7
   6432: obj =   1.557208449e+12 inf =   5.222e+07 (896) 6
Warning: basis matrix is ill-conditioned (cond = 3.87e+13)
   7231: obj =   1.997825908e+12 inf =   4.403e+07 (869) 6
   7976: obj =   2.217542034e+12 inf =   3.166e+07 (770) 5
   8703: obj =   2.390247335e+12 inf =   2.753e+07 (708) 5
   9414: obj =   2.536218815e+12 inf =   2.393e+07 (647) 5
  10117: obj =   2.756054236e+12 inf =   2.163e+07 (593) 5
  10802: obj =   2.935353932e+12 inf =   1.908e+07 (532) 4
  11477: obj =   3.086179517e+12 inf =   1.754e+07 (480) 4
  12150: obj =   3.197893621e+12 inf =   1.628e+07 (450) 5
  12788: obj =   3.298689697e+12 inf =   1.498e+07 (426) 5
  13440: obj =   3.333287446e+12 inf =   1.251e+07 (382) 4
  14083: obj =   3.300325046e+12 inf =   1.077e+07 (340) 5
  14740: obj =   3.310991662e+12 inf =   8.777e+06 (313) 4
  15392: obj =   3.306829795e+12 inf =   8.130e+06 (298) 5
  16062: obj =   3.167939175e+12 inf =   7.197e+06 (289) 4
  16693: obj =   2.836111646e+12 inf =   5.763e+06 (273) 5
  17333: obj =   2.697862855e+12 inf =   4.519e+06 (120) 4
  17986: obj =   2.620014273e+12 inf =   3.939e+06 (102) 4
  18632: obj =   2.450996742e+12 inf =   3.343e+06 (84) 4
  19275: obj =   2.361044575e+12 inf =   2.870e+06 (67) 5
  19909: obj =   2.364960423e+12 inf =   2.286e+06 (42) 4
  20496: obj =   2.398133956e+12 inf =   1.956e+06 (17) 5
  21090: obj =   2.435527949e+12 inf =   1.681e+06 (9) 4
  21699: obj =   2.413369321e+12 inf =   1.192e+06 (6) 4
  22320: obj =   2.393698876e+12 inf =   9.176e+05 (3) 4
  22924: obj =   2.418149249e+12 inf =   7.777e+05 (3) 4
  23536: obj =   2.456471196e+12 inf =   4.530e+05 (1) 4
  24163: obj =   2.463938084e+12 inf =   3.236e+05 (1) 5
  24758: obj =   2.537501175e+12 inf =   2.219e+05 (1) 4
  25372: obj =   2.761056031e+12 inf =   8.529e+03 (1) 4
  25379: obj =   2.768162266e+12 inf =   5.804e-10 (0)
* 25987: obj =   2.158242562e+12 inf =   2.025e-10 (20582) 4
* 26551: obj =   1.925093660e+12 inf =   2.896e-10 (21523) 4
* 27122: obj =   1.787398888e+12 inf =   7.045e-11 (20932) 4
* 27692: obj =   1.702434348e+12 inf =   4.385e-11 (20702) 4
* 28248: obj =   1.650294749e+12 inf =   3.350e-11 (21557) 4
* 28796: obj =   1.580038598e+12 inf =   3.951e-11 (21968) 4
* 29354: obj =   1.534711760e+12 inf =   1.175e-10 (20721) 3
* 29893: obj =   1.466926968e+12 inf =   4.747e-11 (20236) 4
* 30443: obj =   1.429829217e+12 inf =   8.806e-11 (20750) 4
* 30982: obj =   1.382588612e+12 inf =   4.245e-11 (21187) 4
* 31524: obj =   1.332959764e+12 inf =   4.674e-11 (20884) 4
* 32068: obj =   1.294901926e+12 inf =   1.005e-09 (20832) 4
* 32634: obj =   1.266883149e+12 inf =   3.482e-11 (21776) 4
* 33171: obj =   1.239946291e+12 inf =   5.405e-11 (21040) 3
* 33699: obj =   1.214338386e+12 inf =   1.414e-10 (20622) 4
* 34255: obj =   1.193132164e+12 inf =   4.995e-10 (20939) 4
* 34825: obj =   1.164320608e+12 inf =   3.331e-10 (20424) 4
* 35402: obj =   1.139617531e+12 inf =   3.527e-10 (20299) 4
* 35977: obj =   1.118391802e+12 inf =   7.986e-10 (20629) 4
* 36550: obj =   1.096988040e+12 inf =   7.700e-11 (21062) 4
* 37111: obj =   1.085799604e+12 inf =   2.442e-10 (20643) 5
* 37638: obj =   1.068425235e+12 inf =   1.703e-10 (19916) 3
* 38194: obj =   1.048971848e+12 inf =   2.224e-09 (20362) 4
* 38770: obj =   1.028679103e+12 inf =   4.162e-11 (20350) 4
* 39339: obj =   1.013540720e+12 inf =   1.392e-10 (19999) 4
* 39893: obj =   9.930978366e+11 inf =   8.707e-11 (20708) 4
* 40453: obj =   9.796719349e+11 inf =   4.438e-11 (20903) 4
* 41015: obj =   9.681578266e+11 inf =   2.354e-10 (21139) 4
* 41586: obj =   9.585606262e+11 inf =   2.225e-10 (19089) 4
* 42156: obj =   9.460243128e+11 inf =   3.565e-09 (18745) 4
* 42715: obj =   9.350227917e+11 inf =   4.146e-10 (20508) 4
* 43275: obj =   9.228013875e+11 inf =   9.245e-11 (20939) 4
* 43827: obj =   9.086347137e+11 inf =   3.458e-09 (21110) 4
* 44394: obj =   9.005433091e+11 inf =   4.177e-10 (19865) 4
* 44945: obj =   8.867782398e+11 inf =   2.621e-10 (19060) 4
* 45510: obj =   8.790512195e+11 inf =   9.388e-09 (18835) 4
* 46061: obj =   8.681472435e+11 inf =   3.449e-10 (20356) 4
* 46596: obj =   8.596081639e+11 inf =   4.158e-11 (18696) 4
* 47150: obj =   8.506614835e+11 inf =   4.021e-11 (19783) 4
* 47707: obj =   8.449280194e+11 inf =   1.998e-10 (20033) 3
* 48269: obj =   8.390258346e+11 inf =   7.966e-11 (19288) 4
* 48810: obj =   8.326208381e+11 inf =   4.130e-11 (19241) 4
* 49362: obj =   8.250594378e+11 inf =   1.105e-09 (20996) 4
* 49905: obj =   8.153308057e+11 inf =   4.984e-11 (20678) 5
* 50482: obj =   8.110896082e+11 inf =   3.649e-11 (18202) 4
* 51050: obj =   8.057618924e+11 inf =   4.811e-11 (19729) 4
* 51553: obj =   8.025670641e+11 inf =   4.698e-11 (20491) 3
* 52104: obj =   7.991011360e+11 inf =   3.623e-11 (19061) 5
* 52644: obj =   7.953395908e+11 inf =   1.283e-09 (19408) 4
* 53199: obj =   7.901761660e+11 inf =   3.526e-11 (19385) 4
* 53758: obj =   7.873566599e+11 inf =   3.632e-09 (18135) 4
* 54308: obj =   7.837336807e+11 inf =   4.953e-09 (19246) 4
* 54851: obj =   7.791330358e+11 inf =   1.498e-10 (16986) 4
* 55414: obj =   7.756339730e+11 inf =   2.921e-11 (18809) 5
* 55974: obj =   7.721005928e+11 inf =   3.667e-11 (17765) 4
* 56544: obj =   7.699319087e+11 inf =   7.794e-11 (18840) 4
* 57099: obj =   7.663024595e+11 inf =   6.139e-11 (20784) 5
* 57668: obj =   7.633020401e+11 inf =   9.195e-10 (18249) 4
* 58204: obj =   7.593711569e+11 inf =   1.195e-10 (18681) 4
* 58769: obj =   7.563209943e+11 inf =   2.777e-08 (19607) 4
* 59318: obj =   7.527593338e+11 inf =   1.842e-10 (19006) 4
* 59851: obj =   7.478381314e+11 inf =   6.712e-11 (18120) 5
* 60404: obj =   7.450004720e+11 inf =   7.323e-11 (20013) 4
* 60965: obj =   7.419547814e+11 inf =   3.066e-11 (16696) 5
* 61566: obj =   7.395087767e+11 inf =   5.351e-11 (18648) 3
* 62136: obj =   7.354317529e+11 inf =   1.459e-09 (18376) 5
* 62715: obj =   7.308762619e+11 inf =   4.556e-11 (19564) 4
* 63281: obj =   7.277068108e+11 inf =   9.515e-11 (17598) 4
Warning: basis matrix is ill-conditioned (cond = 2.79e+13)
* 63844: obj =   7.244675915e+11 inf =   5.771e-09 (17540) 5
* 64397: obj =   7.212341822e+11 inf =   3.012e-11 (18530) 3
* 64944: obj =   7.144726931e+11 inf =   4.581e-11 (18245) 5
* 65509: obj =   7.034324940e+11 inf =   3.242e-11 (20383) 4
Warning: basis matrix is ill-conditioned (cond = 9.78e+13)
* 66085: obj =   7.005775682e+11 inf =   5.999e-11 (19251) 5
* 66641: obj =   6.983402701e+11 inf =   2.822e-11 (18477) 4
* 67231: obj =   6.973531818e+11 inf =   1.064e-10 (18072) 4
* 67806: obj =   6.965149230e+11 inf =   3.271e-11 (18953) 5
* 68403: obj =   6.882509843e+11 inf =   2.645e-11 (19302) 4
* 68985: obj =   6.734492432e+11 inf =   2.714e-11 (20285) 5
* 69558: obj =   6.714515697e+11 inf =   8.552e-10 (20422) 3
* 70119: obj =   6.703035353e+11 inf =   3.598e-11 (18682) 5
* 70671: obj =   6.692242422e+11 inf =   2.730e-11 (19213) 4
* 71217: obj =   6.679471974e+11 inf =   3.874e-11 (18807) 4
* 71804: obj =   6.673678214e+11 inf =   5.353e-10 (18158) 3
* 72341: obj =   6.667308627e+11 inf =   1.239e-09 (19127) 4
* 72923: obj =   6.662535365e+11 inf =   6.274e-10 (18658) 4
* 73511: obj =   6.657110708e+11 inf =   2.283e-10 (18928) 5
* 74094: obj =   6.651777388e+11 inf =   9.694e-11 (19167) 4
* 74652: obj =   6.645463443e+11 inf =   1.221e-10 (20119) 4
* 75163: obj =   6.638297878e+11 inf =   6.187e-09 (17815) 4
* 75698: obj =   6.633522475e+11 inf =   3.442e-11 (20047) 3
* 76210: obj =   6.630618854e+11 inf =   5.611e-09 (18865) 4
* 76743: obj =   6.626816110e+11 inf =   1.393e-10 (17220) 4
* 77287: obj =   6.621516171e+11 inf =   3.030e-11 (18959) 4
* 77821: obj =   6.615578672e+11 inf =   3.630e-11 (16425) 4
* 78360: obj =   6.610769130e+11 inf =   7.727e-11 (18384) 5
* 78877: obj =   6.602758504e+11 inf =   3.614e-11 (17630) 3
* 79414: obj =   6.597106652e+11 inf =   4.720e-08 (17839) 4
* 79920: obj =   6.592922899e+11 inf =   3.796e-11 (18253) 4
* 80426: obj =   6.587839053e+11 inf =   4.487e-11 (18850) 4
* 80964: obj =   6.581787841e+11 inf =   6.943e-10 (19398) 3
* 81481: obj =   6.574958417e+11 inf =   3.628e-11 (17607) 4
* 82026: obj =   6.568904072e+11 inf =   3.058e-11 (21127) 4
* 82587: obj =   6.561451991e+11 inf =   1.992e-10 (19429) 4
* 83138: obj =   6.555013468e+11 inf =   1.555e-08 (17728) 4
* 83695: obj =   6.547781165e+11 inf =   3.649e-11 (18883) 4
* 84240: obj =   6.542205592e+11 inf =   8.417e-11 (16174) 5
* 84808: obj =   6.536956751e+11 inf =   3.836e-11 (18942) 4
* 85394: obj =   6.531531745e+11 inf =   6.101e-11 (16982) 3
* 85964: obj =   6.526393354e+11 inf =   9.627e-08 (18941) 4
* 86488: obj =   6.516626711e+11 inf =   3.801e-11 (17574) 5
* 87037: obj =   6.506464391e+11 inf =   7.495e-08 (19511) 5
* 87550: obj =   6.492967800e+11 inf =   7.036e-11 (18653) 4
* 88117: obj =   6.475154251e+11 inf =   3.412e-11 (15665) 4
* 88676: obj =   6.456095737e+11 inf =   3.239e-11 (18438) 4
* 89233: obj =   6.450766178e+11 inf =   5.465e-09 (18014) 5
* 89798: obj =   6.438805732e+11 inf =   4.433e-11 (18887) 4
* 90360: obj =   6.427565611e+11 inf =   3.142e-11 (18241) 4
* 90919: obj =   6.421731682e+11 inf =   1.257e-08 (19813) 4
* 91453: obj =   6.401385800e+11 inf =   5.573e-11 (18342) 4
* 91992: obj =   6.383668001e+11 inf =   4.956e-11 (18371) 4
* 92556: obj =   6.373349137e+11 inf =   1.490e-09 (19239) 4
* 93130: obj =   6.363977199e+11 inf =   6.822e-09 (16997) 4
* 93667: obj =   6.340249834e+11 inf =   1.106e-09 (15456) 4
* 94191: obj =   6.321168971e+11 inf =   3.789e-11 (18696) 4
* 94753: obj =   6.291158843e+11 inf =   4.881e-11 (17621) 4
* 95317: obj =   6.277555328e+11 inf =   8.964e-10 (20693) 4
* 95856: obj =   6.269108997e+11 inf =   1.931e-10 (17491) 3
* 96385: obj =   6.263430694e+11 inf =   3.147e-11 (14718) 4
* 96937: obj =   6.257828221e+11 inf =   2.636e-10 (16029) 3
* 97489: obj =   6.248805236e+11 inf =   4.120e-11 (14114) 4
* 98059: obj =   6.239459087e+11 inf =   4.842e-11 (16730) 5
* 98564: obj =   6.225055244e+11 inf =   3.271e-11 (11967) 3
* 99106: obj =   6.213830373e+11 inf =   1.688e-10 (14546) 4
* 99656: obj =   6.198717724e+11 inf =   3.013e-11 (15299) 5
*100249: obj =   6.190958028e+11 inf =   5.271e-10 (19801) 4
*100816: obj =   6.186886468e+11 inf =   2.763e-11 (13830) 4
Perturbing LP to avoid stalling [101184]...
*101396: obj =   6.185768616e+11 inf =   2.725e-11 (15930) 3
*101975: obj =   6.180519214e+11 inf =   7.678e-09 (14254) 4
*102493: obj =   6.167074369e+11 inf =   1.195e-08 (14336) 3
*103014: obj =   6.154665015e+11 inf =   1.539e-08 (13653) 4
*103490: obj =   6.130384122e+11 inf =   1.624e-08 (9704) 4
*103997: obj =   6.111050187e+11 inf =   1.712e-08 (9818) 5
*104571: obj =   6.097058839e+11 inf =   1.246e-08 (9644) 3
*105113: obj =   6.086403566e+11 inf =   1.638e-08 (16110) 5
*105681: obj =   6.078757203e+11 inf =   2.364e-08 (8662) 4
*106263: obj =   6.074228001e+11 inf =   2.850e-08 (14232) 3
*106797: obj =   6.070631019e+11 inf =   1.963e-08 (10837) 5
*107364: obj =   6.059592360e+11 inf =   2.026e-08 (12769) 5
*107925: obj =   6.057433043e+11 inf =   2.044e-08 (12951) 4
*108505: obj =   6.055491134e+11 inf =   2.245e-08 (7093) 4
*109117: obj =   6.055122774e+11 inf =   2.155e-08 (7220) 3
*109699: obj =   6.052552144e+11 inf =   2.155e-08 (7209) 5
*110307: obj =   6.052329371e+11 inf =   2.154e-08 (10836) 2
*110886: obj =   6.048025478e+11 inf =   2.373e-08 (9370) 4
*111421: obj =   6.042353809e+11 inf =   3.484e-08 (14574) 1
*111970: obj =   6.040771053e+11 inf =   4.239e-08 (5113) 3
*112521: obj =   6.039847634e+11 inf =   1.210e-06 (6958) 4
*113082: obj =   6.039811589e+11 inf =   6.777e-06 (6005) 3
*113605: obj =   6.034104148e+11 inf =   2.262e-06 (6216) 3
*114173: obj =   6.034077040e+11 inf =   2.255e-06 (5458) 3
*114725: obj =   6.030965311e+11 inf =   2.524e-06 (12924) 3
*115249: obj =   6.029058089e+11 inf =   2.536e-06 (11601) 3
*115845: obj =   6.028295762e+11 inf =   1.045e-05 (3894) 4
*116479: obj =   6.027435295e+11 inf =   1.042e-05 (3583) 4
*117125: obj =   6.027422455e+11 inf =   1.043e-05 (5532) 4
*117767: obj =   6.027391596e+11 inf =   1.838e-05 (2658) 3
*118432: obj =   6.026033521e+11 inf =   2.944e-05 (2938) 5
*119227: obj =   6.026021094e+11 inf =   3.151e-05 (3066) 3
*119870: obj =   6.026017086e+11 inf =   5.132e-05 (2575) 5
*120535: obj =   6.025935656e+11 inf =   9.020e-05 (5358) 3
*121241: obj =   6.025935630e+11 inf =   1.077e-04 (6716) 3
*121905: obj =   6.025812415e+11 inf =   9.508e-05 (829) 5
*122520: obj =   6.025681311e+11 inf =   1.174e-04 (5137) 4
*123201: obj =   6.025681311e+11 inf =   1.400e-04 (355) 3
*123799: obj =   6.025555305e+11 inf =   1.010e-04 (3697) 6
*124405: obj =   6.025552233e+11 inf =   8.746e-05 (2171) 5
*125041: obj =   6.025552206e+11 inf =   1.167e-04 (425) 4
Warning: basis matrix is ill-conditioned (cond = 1.05e+14)
*125615: obj =   6.025208383e+11 inf =   1.154e-04 (5061) 6
*126091: obj =   6.025208160e+11 inf =   1.199e-04 (1744) 5
*126667: obj =   6.025208157e+11 inf =   1.304e-04 (58) 4
*127203: obj =   6.025208133e+11 inf =   1.237e-04 (610) 3
*127791: obj =   6.025208131e+11 inf =   1.189e-04 (1218) 8
Removing LP perturbation [127991]...
*127991: obj =   6.025208131e+11 inf =   1.023e-07 (0) 2
OPTIMAL LP SOLUTION FOUND
Time used:   1093.7 secs
Memory used: 161.3 Mb (169150388 bytes)
Writing basic solution to 'C:\Users\lukas\AppData\Local\Temp\tmpwgdr34og.glpk.raw'...
252552 lines were written
Traceback (most recent call last):
  File "runme.py", line 106, in <module>
    report_sites_name=report_sites_name)
  File "C:\Users\lukas\OneDrive\Desktop\Programme_Installation\urbs\urbs-1.0.1\urbs-1.0.1\urbs\runfunctions.py", line 107, in run_scenario
    save(prob, os.path.join(result_dir, '{}.h5'.format(sce)))
  File "C:\Users\lukas\OneDrive\Desktop\Programme_Installation\urbs\urbs-1.0.1\urbs-1.0.1\urbs\saveload.py", line 31, in save
    import tables
  File "C:\Users\lukas\miniconda3\envs\urbs\lib\site-packages\tables\__init__.py", line 99, in <module>
    from .utilsextension import (
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

(urbs) C:\Users\lukas\OneDrive\Desktop\Programme_Installation\urbs\urbs-1.0.1\urbs-1.0.1>python comp.py
Traceback (most recent call last):
  File "comp.py", line 259, in <module>
    compare_scenarios(list(reversed(result_files)), comp_filename)
  File "comp.py", line 154, in compare_scenarios
    costs = pd.concat(costs, axis=1, keys=scenario_names)
  File "C:\Users\lukas\miniconda3\envs\urbs\lib\site-packages\pandas\core\reshape\concat.py", line 228, in concat
    copy=copy, sort=sort)
  File "C:\Users\lukas\miniconda3\envs\urbs\lib\site-packages\pandas\core\reshape\concat.py", line 262, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

**Comment by ojdo** [comment]
You seem to have some dependency problem somewhere around the `import tables` line; some DLL that is mentioned in its `__init__.py` seems not to be present. As the urbs environment installs `pytables=3.6.1` for that, I would dig for a bug in that direction. Or maybe you just do not have pytables (or one of its binary depdencies, its [docs](https://www.pytables.org/usersguide/installation.html) list the hdf5, zlib, blosc, or bz2 as possible candidates) installed?

**Comment by ojdo** [comment]
See #294 for a workaround
