### ISSUE TITLE
Python version mismatch between README and env.yml

### ISSUE THREAD

**Issue by jannemannX** [tum-ens/urbs#321]
The README recommends using python 3.6 but the urbs-env.yml specifically requests 3.12.2 to be installed. "dependencies: - python=3.12.2"

Switching later does not work anyway. I assume the README just hasn't been updated?

Small thing, but the anaconda environment is called "urbs-env" exactly as the .yml file name, so the proposed "conda activate urbs" command will not work.

Also, maybe it makes sense to set the solver to glpk per default instead of gurobi, as glpk is one of the installed packages and gurobi seemingly needs a separate installation. Following the installation and Get Started instructions crashes the program when trying to use Gurobi.

**Comment by bereba** [comment]
Hi, thank you for your feedback. The installation README has been adjusted now to the latest python version and we added some additional support features for windows users. Be aware that we also changed the approach from conda environments to more lightweight python virtual environments.

**Comment by jannemannX** [comment]
Thanks for the fix!
Is there any plan to create a new release? As the current release from 2019 seems quite outdated.

Otherwise, marking it as deprecated might be useful to spare (people like me) some trouble. :)
