### ISSUE TITLE
issue with runme.py

### ISSUE THREAD

**Issue by dacoex** [tum-ens/urbs#36]
After cloning from github:

```
  File "urbs.py", line 1583, in report
    timeseries[(co, sit)].to_excel(writer, sheet_name)

  File "C:\Users\USER\AppData\Local\Continuum\Anaconda\lib\site-packages\pandas\core\frame.py", line 1252, in to_excel
    raise NotImplementedError("Writing as Excel with a MultiIndex is "

NotImplementedError: Writing as Excel with a MultiIndex is not yet implemented.
```

**Comment by ojdo** [comment]
Can you confirm that your pandas version is up-to-date (0.17.0)? There have been some changes in their Excel I/O code.

**Comment by dacoex** [comment]
Problem is gone.

But I see a lot of other issues with matplotlib. 

There is something wrong with the Anaconda.

**Comment by ojdo** [comment]
Thanks for clarifying. Please report separately if problem persists with a completely updated Anaconda. The pandas 0.17.0 also changed some (to be fair: undocumented) behaviour that required action here (c.f. #31 and #33).

**Comment by dacoex** [comment]
Works with recent WinPython (https://winpython.github.io/)

So an issue of Anaconda dependencies.
Maybe you'd like to add this to the homepage.
Also, we could suggest to WinPython to include the solvers (GLPK , coopr) in their standard distro.
What do you think?
