### ISSUE TITLE
Maximal power gradient

### ISSUE THREAD

**Issue by smuellr** [tum-ens/urbs#40]
For some scenarios it is more accurate or necessary to limit the maximal power gradient of a process, especially when using timesteps smaller than 1h.

An implementation would need a new column "max-grad" in the process sheet and a new constraint in urbs.py.
The new technical process parameter, its description and the new constraint should be mentioned in the mathematical documentation and the new additional column displayed in the workflow.
The derivative might be included in the report and mentioned in the explanation of the report function.

A first approach can be found here:
https://github.com/smuellr/urbs/tree/max-power-gradient

**Comment by ojdo** [comment]
Just one comment: for large power plants, the maximal gradient can even play a role for durations (much) longer than one hour.

**Comment by ojdo** [comment]
Closed by PR #43.
