### ISSUE TITLE
Add start-up costs for power plants

### ISSUE THREAD

**Issue by smuellr** [tum-ens/urbs#57]
The addition of start-up costs in addition to maximal power gradients could further increase the accuracy of scheduling (and consequently also investment) especially with power plants like coal plants.

This might be implemented by adding a new column "start-up-cost" in the "Process" sheet and adding a new var cost type like `C(p) * (1 - S(t-1,p)) * S(t,p)` where C are the start-up costs for the process and S is the on/off status for the process at a timestep.

In Python it might roughly look like this:

    sum((1 - m.stat_pro[(tm-1,) + p]) 
        * m.stat_pro[(tm,) + p] 
        * m.process.loc[p]['start-up-costs']
        for tm in m.tm[1:] for p in m.pro_tuples)

with a new variable `m.stat_pro`

**Comment by ojdo** [comment]
Note that this proposed formulation is non-linear due to the product of variable `m.stat_pro` with itself. However, there are ways to "detect" a rising edge in the activity of a process with only (mixed-integer) linear terms, e.g.: http://arxiv.org/pdf/1408.2644

**Comment by ojdo** [comment]
Closed by #70.
