### ISSUE TITLE
DSM appearing twice in commodity balance?

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#69]
The effect of demand-side-management might be exaggerated right now. When looking at [`res_vertex_rule`](https://github.com/tum-ens/urbs/blob/747f1cae2c1063ebe9b6bb17c2d510f99f8e40a4/urbs.py#L662-L664), I see:

    if (sit, com) in m.dsm_site_tuples:
        power_surplus -= m.dsm_up[tm,sit,com]
        power_surplus += sum(m.dsm_down[t,tm,sit,com] for t in dsm_time_tuples(tm, m.timesteps[1:], m.dsm.loc[sit,com]['delay']))

And further down in [`commodity_balance`](https://github.com/tum-ens/urbs/blob/747f1cae2c1063ebe9b6bb17c2d510f99f8e40a4/urbs.py#L1161-L1166), there is a seemingly identical construct:

    for site, commodity in m.dsm_site_tuples:
        # upshifted demand increases demand
        # downshifted demand decreses demand
        if site == sit and commodity == com:
            balance += m.dsm_up[tm,sit,com]
            balance -= sum(m.dsm_down[t,tm,sit,com] for t in dsm_time_tuples(tm, m.timesteps[1:], m.dsm.loc[sit,com]['delay']))

As `res_vertex_rule` uses `commodity_balance` to initialise its balancing variable `power_surplus = - commodity_balance(m, tm, sit, com)`. So all in all, each `dsm_up` and `dsm_down` seems to appear twice now when calculating the balance.

**Comment by maledo** [comment]
Added by restructuring the vertex rule with: https://github.com/tum-ens/urbs/commit/45a875289883f34caab3945f952acafba5f3fc8c
