### ISSUE TITLE
Change readthedocs.org to readthedocs.io

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#74]
Some time ago, readthedocs changed their default domain name for serving project documentations from readthedocs.org to readthedocs.io. In order to avoid always triggering redirects, we should change all links in this project to point to the new encouraged domains. This includes 

  * the docs badge at the top of README.md
  * plaintext links in README.md section **Next steps**
  * possibly some absolute links within in folder `doc`.

**Comment by maledo** [comment]
Closed by commit d3e380ec71d5136c4fdcb02cddba326ac6a73721, as there was no direct mentioning of readthedocs.org in the doc folder
