### ISSUE TITLE
Remove/rework doc/report.rst

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#81]
The documentation page `doc/report.rst` has several broken `literalinclude` sections, probably due to changes in the comments that were used to delimit where the displayed code sections start and end. In the current form, the document is no longer helpful. It either needs an almost complete rewrite or - probably easier - should be removed. This comprises:
- the file itself
- the link to it in `doc/index.rst` and
- all sentences that use `:ref:`report-function`` to link to the page

**Comment by lodersky** [comment]
Documentation was rewritten with release 1.0.
